# Generated by Django 5.2.5 on 2025-08-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
