# Generated by Django 5.2.5 on 2025-08-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='payment_date',
            new_name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='member',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='member',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
